title: Александр Крушин
description: Запускаю собственные проекты. До этого был директором по маркетингу портала Рамблер и директором по развитию «Афиши». Обожаю медиа, контент и новые технологии.
email: akrushin@gmail.com
telegram_url: https://t.me/krushin
baseurl: ""
url: "https://krushin.me"
permalink: /ru/notes/:title/
default_lang: ru
languages:
  - ru
  - en
lang: ru
locale: ru_RU
logo: /images/logo.jpg
author:
  name: Александр Крушин
  bio: Запускаю собственные проекты. До этого был директором по маркетингу портала <span class="rambler">Рамблер</span> и директором по развитию <span class="afisha">«Афиши»</span>. Обожаю медиа, контент и новые технологии.
  avatar: https://www.gravatar.com/avatar/173303ff8da78411c197beb08a15626f

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

collections:
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
